### ISSUE TITLE
Innacurate coordinates when image is in portrait orientation

### ISSUE THREAD

**Issue by jakewarrenblack** [younesZdDz/react-bbox-annotator#4]
Bbox-annotator works nicely for images in landscape orientation, but the bounding box size and position (top, left, width and height) are completely innacurate when used for portrait images. In these examples, I've used bbox annotator to draw bounding boxes on both a landscape and a portrait image, converted the annotation coordinates to PASCAL VOC format, and uploaded the image and its annotation to Roboflow for viewing:

Here's the portrait image locally, before uploading:
![image](https://user-images.githubusercontent.com/47800618/232245714-cc27c15c-b488-44e3-8e30-b898c9ac07f0.png)

And here it is after upload:
![image](https://user-images.githubusercontent.com/47800618/232245722-cc7502f8-de3e-466e-9cce-152789f4d738.png)

For comparison, here's the landscape image before upload:
![image](https://user-images.githubusercontent.com/47800618/232245744-eb2c1bd8-a07f-460a-a417-ae8eb3d01ce8.png)

And after upload:
![image](https://user-images.githubusercontent.com/47800618/232245758-0cb4d19e-4e48-46a9-a72f-f6e97015158b.png)

The annotations produced by bbox-annotator are these:
![image](https://user-images.githubusercontent.com/47800618/232245801-27f4d0e3-7202-4df0-980d-77f03b897cc4.png)

I'm not entirely sure what its purpose is, but the multiplier value used for the landscape image was 9.73913043478261, and the one used for the portrait image was 4.608695652173913

Can you make any suggestion as to what might be causing this problem, and how it could be fixed? I'd happily open a PR if you can suggest the cause and possible solution. Cheers!

**Comment by jakewarrenblack** [comment]
Fixed. The problem actually only occurred when providing bbox annotator with a mix of both landscape and portrait images, in which case it would only accurately annotate one type or the other. However, when you provide it with *only* portrait or *only* landscape, it's fine. 

So the solution to this was just to recalculate the multiplier every time the entries are set. Note that the entries objects here have been changed to also contain the image's original width, which is what `entry.imgWidth` refers to.

```js
    useEffect(() => {
        // check if there are any entries present which are not undefined
        if (entries.some((entry) => entry !== undefined)) {
            setSubmissionEntries(
              entries.map((entry) => {
                      const multiplier = entry.imgWidth / maxWidth
                      return {
                          width: Math.round(entry.width * multiplier),
                          height: Math.round(entry.height * multiplier),
                          top: Math.round(entry.top * multiplier),
                          left: Math.round(entry.left * multiplier),
                          label: entry.label,
                          fileName: entry.fileName,
                          imgWidth: entry.imgWidth,
                          imgHeight: entry.imgHeight
                      }
              })
            );
        }
    }, [entries, multiplier]);
```

Cheers 🙂

**Comment by younesZdDz** [comment]
Hello @jakewarrenblack,

Thanks for the feedback. Could you make a PR 
... I'll make sure to review it this week .
Thank you ever so much 😃

**Comment by jakewarrenblack** [comment]
> Hello @jakewarrenblack,
> 
> Thanks for the feedback. Could you make a PR ... I'll make sure to review it this week . Thank you ever so much 😃

Can do, but keep in mind the issue I encountered wouldn't actually occur for anybody just using react-bbox-annotator as it is. In my case, I'm using my own modified version of it which accepts an array of files from react-dropzone-uploader, which means my version of react-bbox-annotator displays a whole gallery with previous/next buttons, rather than just one image at a time. 

The problem I described with portrait/landscape coordinates being innacurate would never happen if react-bbox-annotator is left the way it is, and accepts only one image at a time 🤷‍♀️

**Comment by younesZdDz** [comment]
hey @jakewarrenblack... I see in that case let's keep the issue closed. 
Thank for sharing
